
// Objective-C API for talking to the following Go packages
//
//	github.com/sger/gomobile-examples/log
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Log_FRAMEWORK_H__
#define __Log_FRAMEWORK_H__

#include "Log.objc.h"
#include "Universe.objc.h"

#endif
