// Objective-C API for talking to github.com/sger/gomobile-examples/log Go package.
//   gobind -lang=objc github.com/sger/gomobile-examples/log
//
// File is generated by gobind. Do not edit.

#ifndef __Log_H__
#define __Log_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* LogSay(NSString* str);

#endif
